Repository webpack/webpack-dev-server, pull requests merged in 2018-08, with the labels that each got.

#1401 fix(examples/cli): correct template path in `open-page` example
  examples/cli/open-page/webpack.config.js
Labels: semver: patch, status: approved, type: bug

#1462 chore(.github/CODEOWNERS): add code owners
  .github/CODEOWNERS
Labels: pr: review, priority: 4 (nice to have), semver: patch, status: pending, type: chore

#1460 docs(readme): remove obsolete maintenance note
  README.md
Labels: pr: review, priority: 3 (important), semver: patch, severity: 5 (confusing), status: pending, type: docs

#1429 refactor(package): drop `array-includes` (`dependencies`)
  bin/webpack-dev-server.js
  lib/Server.js
  lib/polyfills.js
  package-lock.json
  package.json
Labels: pr: review, priority: 3 (important), semver: patch, status: pending, type: refactor

#1409 fix(schema): allow the `output` filename to be a `{Function}`
  lib/optionsSchema.json
  test/Validation.test.js
Labels: semver: patch, status: approved, type: bug

#1432 fix(bin): handle `process` signals correctly when the server isn't ready yet
  bin/webpack-dev-server.js
  test/cli.test.js
Labels: semver: patch, status: approved, type: bug

#1461 chore(package): add `release` script (`scripts`)
  package-lock.json
  package.json
Labels: semver: patch, status: approved, type: chore

#1467 ci(travis): add build stages
  .gitignore
  .travis.yml
  package-lock.json
  package.json
Labels: semver: patch, status: approved, type: ci

#1472 chore(package): update `webpack-log` v1.1.2...v2.0.0 (`dependencies`)
  package-lock.json
  package.json
Labels: semver: patch, status: pending, type: chore

#1473 chore(package): update `webpack-dev-middleware` v3.1.3...v3.2.0 (`dependencies`)
  package-lock.json
  package.json
Labels: semver: patch, status: pending, type: chore

#1474 chore(package): update `devDependencies`
  package-lock.json
  package.json
Labels: semver: patch, status: pending, type: chore

#1465 refactor(lib/utils): move `createLog` && rename files
  bin/webpack-dev-server.js
  lib/Server.js
  lib/createLog.js
  lib/util/createDomain.js
  lib/utils/addEntries.js
  lib/utils/createDomain.js
  lib/utils/createLogger.js
  test/Entry.test.js
  test/Util.test.js
Labels: semver: patch, status: pending, type: refactor

#1470 refactor(bin): move options and helpers into separate files
  bin/options.js
  bin/utils.js
  bin/webpack-dev-server.js
Labels: semver: patch, status: approved, type: refactor

#1466 refactor(Server): move certificate generation to it's own file
  lib/Server.js
  lib/utils/createCertificate.js
  test/Util.test.js
Labels: semver: patch, status: approved, type: refactor

#1464 refactor(package): migrate to `schema-utils` (`dependencies`)
  bin/webpack-dev-server.js
  lib/OptionsValidationError.js
  lib/Server.js
  lib/options.json
  lib/optionsSchema.json
  package-lock.json
  package.json
  test/Validation.test.js
Labels: semver: patch, status: approved, type: refactor

#1451 fix(Server): don't use `spdy` on `node >= v10.0.0`
  lib/Server.js
  test/Https.test.js
Labels: semver: patch, status: approved, type: bug

#1478 style(utils/addEntries): cleaner variable naming
  lib/utils/addEntries.js
Labels: semver: patch, status: approved, type: style

#1484 chore(package): update `import-local` v1.0.0...2.0.0 (`dependencies`)
  package-lock.json
  package.json
Labels: semver: patch, status: approved, type: chore
