Repository webpack/webpack-dev-server, pull requests merged in 2018-09, with the labels that each got.

#1486 fix(utils/createLogger): ensure `quiet` always takes precedence (`options.quiet`)
  lib/utils/createLogger.js
Labels: semver: patch, status: approved, type: bug

#1487 docs(readme): fix typos
  README.md
Labels: semver: patch, status: approved, type: docs

#1492 fix(package): `yargs` security vulnerability (`dependencies`)
  package-lock.json
  package.json
Labels: semver: patch, status: approved, type: bug

#1498 refactor(package): cross-platform `prepare` script (`scripts`)
  package.json
Labels: semver: patch, status: approved, type: refactor

#1499 chore(package): update `webpack-dev-middleware` v3.2.0...3.3.0 (`dependencies`)
  package-lock.json
  package.json
Labels: semver: patch, status: pending, type: chore
