Repository webpack/webpack-dev-server, pull requests merged in 2018-10, with the labels that each got.

#1520 fix(options): add `writeToDisk` option to schema
  lib/options.json
  test/Validation.test.js
Labels: pr: rework, priority: 3 (important), semver: patch, severity: 4 (inconvenient), status: pending, type: bug

#1537 fix(package): update `sockjs-client` v1.1.5...1.3.0 (`url-parse` vulnerability)
  package-lock.json
  package.json
Labels: priority: 1 (critical), scope: client, semver: patch, severity: 1 (security), status: approved, type: bug

#1531 fix(Server): set `tls.DEFAULT_ECDH_CURVE` to `'auto'`
  lib/Server.js
Labels: scope: http(s), semver: patch, status: approved, type: bug

#1539 chore(PULL_REQUEST_TEMPLATE): allow features
  .github/PULL_REQUEST_TEMPLATE.md
Labels: semver: patch, status: approved, type: chore

#1543 fix(Server): correct `node` version checks
  lib/Server.js
  package-lock.json
  package.json
Labels: semver: patch, status: approved, type: bug

#1555 fix(bin/options): correct check for color support (`options.color`)
  bin/options.js
Labels: priority: 3 (important), scope: cli, semver: patch, severity: 3 (broken), type: bug
